CREATE TABLE MEMBERS (
    ID VARCHAR(30) PRIMARY KEY,
    PW VARCHAR(128) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    CONTACT VARCHAR(20) NOT NULL,
    REGISTERED_TIMESTAMP TIMESTAMP DEFAULT SYSDATE
);